name: Deployment

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      uses: brendanmurty/github-action-ssh@release
      with:
        command: |
          cd ${{ secrets.REMOTE_DIRECTORY }}
          git pull origin master --quiet
          composer install --quiet --no-interaction
          npm install --silent --no-progress --no-fund
          npm install --silent --no-progress --global gulp-cli
          gulp --silent
          php artisan view:clear
          php artisan cache:clear
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}