name: Deploy on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run commands on server
      uses: brendanmurty/github-action-ssh@release
      with:
        command: |
          cd ${{ secrets.REMOTE_DIRECTORY }}
          git pull origin master --quiet
          composer install --no-interaction
          npm install --silent
          php artisan view:clear
          npm run production
          cd ${{ secrets.REMOTE_DIRECTORY }}/.. && sudo ./certbot-auto renew --force-renewal
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
