name: Maintenance

on:
  schedule:
    - cron: "0 23 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      uses: brendanmurty/github-action-ssh@release
      with:
        command: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt autoremove
          sudo apt autoclean
          cd /var/www/html/
          sudo ./certbot-auto renew --force-renewal --no-random-sleep-on-renew
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}